name: pos
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=db2025#
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - posnet

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "8082:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=guillaume.cerceau@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin2025#
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - posnet

volumes:
  postgres-data:
  pgadmin-data:

networks:
  posnet:
